version: '2'
services:
  proxy:
    image: registry:2.2
    volumes: 
      - ./:/var/lib/registry
    command: /var/lib/registry/config.proxy.yml
    ports: 
      - "5000:5000"

  private:
    image: registry:2.2
    volumes: 
      - ./:/var/lib/registry
    command: /var/lib/registry/config.private.yml
    ports: 
      - "5100:5000"

  nexus:
    image: sonatype/nexus3:3.0.2
    volumes: 
      - "nexus-data:/nexus-data"
    ports: 
      - "8081:8081"

volumes:
  nexus-data: {}
