version: '2'

services:
  nexus:
    image: sonatype/nexus3:3.0.1
    volumes: 
      - "nexus-data:/nexus-data"
    ports: 
      - "8081:8081"
      #- "5000:5000"
  # docker-registry:
  #   image: nginx

    

volumes:
  nexus-data: {}
